# services:
#   catalog.api:
#     image: ${DOCKER_REGISTRY-}catalogapi
#     build:
#       context: .
#       dockerfile: Services/Catalog/Catalog.API/Dockerfile

services:
  catalogdb:
    image: postgres
volumes:
  postgres_catalog: null